# Default values for godaddy-webhook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: fred78290/cert-manager-godaddy
  tag: v1.24.6
  pullPolicy: IfNotPresent

groupName: acme.mycompany.com

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

dnsPolicy: "Default"
dnsConfig: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
